<?php
class BoursiersDao extends Manager {
    public function __construct(){
        $this->tableName="boursier";
        $this->className="Boursiers";
    }

    public function add($obj){

    }
    public function update($objet)
    {

    }

    public function addBoursier($ishoused, $id_etudiant,$id_type_bourse,$id_chambre){
        $req = "INSERT INTO boursier (ishoused,id_etudiant,id_type_bourse,id_chambre) VALUE (:ishoused, :id_etudiant, :id_type_bourse, :id_chambre)";
        $row = array(
            'ishoused'=>$ishoused,
            'id_etudiant'=>$id_etudiant,
            'id_type_bourse'=>$id_type_bourse,
            'id_chambre'=>$id_chambre,
        );
        $ligne = $this->executeUpdate($req,$row);
        return $ligne;
    }

    public function findByelement($id, $elementTable)
    {
        return parent::findByelement($id, $elementTable); // TODO: Change the autogenerated stub
    }

    public function findAllBoursiers()
    {
        $sql= "select * from boursier ";
        $req = $this->executeSelect($sql);
        return $req;
    }

}
